"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var register_component_1 = require("./regiseter/register.component");
exports.RegisterComponent = register_component_1.RegisterComponent;
var login_component_1 = require("./login/login.component");
exports.LoginComponent = login_component_1.LoginComponent;
var user_list_component_1 = require("./list/user-list.component");
exports.UserListComponent = user_list_component_1.UserListComponent;
var user_add_component_1 = require("./add/user-add.component");
exports.UserAddComponent = user_add_component_1.UserAddComponent;
var user_edit_component_1 = require("./edit/user-edit.component");
exports.UserEditComponent = user_edit_component_1.UserEditComponent;
var roles_list_component_1 = require("./roles/list/roles-list.component");
exports.RolesListComponent = roles_list_component_1.RolesListComponent;
var user_roles_component_1 = require("./roles/user-roles/user-roles.component");
exports.UserRolesComponent = user_roles_component_1.UserRolesComponent;
var change_password_component_1 = require("./change-password/change-password.component");
exports.ChangePasswordComponent = change_password_component_1.ChangePasswordComponent;
var add_role_dialog_component_1 = require("./roles/add/add-role-dialog.component");
exports.AddRoleDialogComponent = add_role_dialog_component_1.AddRoleDialogComponent;
//# sourceMappingURL=user.barel.js.map